---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Set default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy:    "{{ item.policy }}"
  loop:
    - { direction: in,  policy: deny }
    - { direction: out, policy: allow }

- name: Ensure allowed ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports }}"

- name: Limit SSH brute-force
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
