---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Reset UFW to defaults
  community.general.ufw:
    state: reset

- name: Deny all incoming connections by default
  community.general.ufw:
    rule: deny
    direction: in

- name: Allow all outgoing connections by default
  community.general.ufw:
    rule: allow
    direction: out

- name: Allow specific ports in UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
