---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH (22/tcp)
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP/HTTPS
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_http_ports }}"

- name: Set default policies
  ufw:
    state: enabled
    policy: deny
  notify: reload ufw
