---
- name: Apt update / upgrade
  apt:
    update_cache: true
    upgrade: dist

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install base packages
  apt:
    name:
      - git
      - curl
      - htop
      - fail2ban
    state: present
