---
- name: Backup current sshd_config
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    owner: root
    group: root
    mode: 0600
  when: not backup_done | default(false)
  vars:
    backup_done: true

- name: Deploy custom sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0600"
  notify:
    - Restart ssh
    - Test new SSH port
